PIECE_TYPES = [
    PAWN,
    LANCE,
    KNIGHT,
    SILVER,
    GOLD,
    BISHOP,
    ROOK,
    KING,
] = range(8)
PROM_PIECE_TYPES = [
    PROM_PAWN,
    PROM_LANCE,
    PROM_KNIGHT,
    PROM_SILVER,
    PROM_BISHOP,
    PROM_ROOK,
] = range(8, 14)
HAND_PIECE_TYPES = [
    HAND_PAWN,
    HAND_LANCE,
    HAND_KNIGHT,
    HAND_SILVER,
    HAND_GOLD,
    HAND_BISHOP,
    HAND_ROOK,
] = range(14, 21)
k_dim = len(PIECE_TYPES) + len(PROM_PIECE_TYPES)
K_dim = k_dim + len(HAND_PIECE_TYPES)

Pr_dim = 2
P_dim = 9*9
F_dim = 9*9
T_dim = 9*9

# From https://github.com/TadaoYamaoka/python-dlshogi/blob/master/pydlshogi/common.py
MOVE_DIRECTION = [
    UP, UP_LEFT, UP_RIGHT, LEFT, RIGHT, DOWN, DOWN_LEFT, DOWN_RIGHT, UP2_LEFT, UP2_RIGHT,
    UP_PROMOTE, UP_LEFT_PROMOTE, UP_RIGHT_PROMOTE, LEFT_PROMOTE, RIGHT_PROMOTE, DOWN_PROMOTE, DOWN_LEFT_PROMOTE, DOWN_RIGHT_PROMOTE, UP2_LEFT_PROMOTE, UP2_RIGHT_PROMOTE
] = range(20)
MOVE_DIRECTION_PROMOTED = [
    UP_PROMOTE, UP_LEFT_PROMOTE, UP_RIGHT_PROMOTE, LEFT_PROMOTE, RIGHT_PROMOTE, DOWN_PROMOTE, DOWN_LEFT_PROMOTE, DOWN_RIGHT_PROMOTE, UP2_LEFT_PROMOTE, UP2_RIGHT_PROMOTE
]
MOVE_DIRECTION_LABEL_NUM = len(MOVE_DIRECTION) + len(HAND_PIECE_TYPES)

FEATURES_DIM = K_dim*2 + k_dim*2
OUTPUT_DIM = T_dim * MOVE_DIRECTION_LABEL_NUM